#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-doxia
Version  : 1.0
Release  : 11
URL      : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-core/1.0/doxia-core-1.0.jar
Source0  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-core/1.0/doxia-core-1.0.jar
Source1  : https://repo.maven.apache.org/maven2/org/apache/maven/doxia/doxia-module-fml/1.7/doxia-module-fml-1.7.jar
Source2  : https://repo.maven.apache.org/maven2/org/apache/maven/doxia/doxia-module-fml/1.7/doxia-module-fml-1.7.pom
Source3  : https://repo.maven.apache.org/maven2/org/apache/maven/doxia/doxia-module-xhtml/1.7/doxia-module-xhtml-1.7.jar
Source4  : https://repo.maven.apache.org/maven2/org/apache/maven/doxia/doxia-module-xhtml/1.7/doxia-module-xhtml-1.7.pom
Source5  : https://repo.maven.apache.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-10/doxia-sink-api-1.0-alpha-10.pom
Source6  : https://repo.maven.apache.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.7/doxia-sink-api-1.7.jar
Source7  : https://repo.maven.apache.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.7/doxia-sink-api-1.7.pom
Source8  : https://repo.maven.apache.org/maven2/org/apache/maven/doxia/doxia/1.7/doxia-1.7.pom
Source9  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-core/1.0/doxia-core-1.0.pom
Source10  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-core/1.1.2/doxia-core-1.1.2.pom
Source11  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-core/1.2/doxia-core-1.2.jar
Source12  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-core/1.2/doxia-core-1.2.pom
Source13  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-core/1.4/doxia-core-1.4.jar
Source14  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-core/1.4/doxia-core-1.4.pom
Source15  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-core/1.5/doxia-core-1.5.jar
Source16  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-core/1.5/doxia-core-1.5.pom
Source17  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-core/1.6/doxia-core-1.6.jar
Source18  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-core/1.6/doxia-core-1.6.pom
Source19  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-core/1.7/doxia-core-1.7.jar
Source20  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-core/1.7/doxia-core-1.7.pom
Source21  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-core/1.8/doxia-core-1.8.jar
Source22  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-core/1.8/doxia-core-1.8.pom
Source23  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-logging-api/1.1.2/doxia-logging-api-1.1.2.jar
Source24  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-logging-api/1.1.2/doxia-logging-api-1.1.2.pom
Source25  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-logging-api/1.1/doxia-logging-api-1.1.jar
Source26  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-logging-api/1.1/doxia-logging-api-1.1.pom
Source27  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-logging-api/1.2/doxia-logging-api-1.2.jar
Source28  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-logging-api/1.2/doxia-logging-api-1.2.pom
Source29  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-logging-api/1.4/doxia-logging-api-1.4.jar
Source30  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-logging-api/1.4/doxia-logging-api-1.4.pom
Source31  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-logging-api/1.5/doxia-logging-api-1.5.pom
Source32  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-logging-api/1.6/doxia-logging-api-1.6.jar
Source33  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-logging-api/1.6/doxia-logging-api-1.6.pom
Source34  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-logging-api/1.7/doxia-logging-api-1.7.jar
Source35  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-logging-api/1.7/doxia-logging-api-1.7.pom
Source36  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-logging-api/1.8/doxia-logging-api-1.8.jar
Source37  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-logging-api/1.8/doxia-logging-api-1.8.pom
Source38  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-apt/1.0/doxia-module-apt-1.0.jar
Source39  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-apt/1.0/doxia-module-apt-1.0.pom
Source40  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-apt/1.6/doxia-module-apt-1.6.jar
Source41  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-apt/1.6/doxia-module-apt-1.6.pom
Source42  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-apt/1.7/doxia-module-apt-1.7.jar
Source43  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-apt/1.7/doxia-module-apt-1.7.pom
Source44  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-apt/1.8/doxia-module-apt-1.8.jar
Source45  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-apt/1.8/doxia-module-apt-1.8.pom
Source46  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-fml/1.0/doxia-module-fml-1.0.jar
Source47  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-fml/1.0/doxia-module-fml-1.0.pom
Source48  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-fml/1.1.2/doxia-module-fml-1.1.2.pom
Source49  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-fml/1.2/doxia-module-fml-1.2.jar
Source50  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-fml/1.2/doxia-module-fml-1.2.pom
Source51  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-fml/1.2/doxia-module-fml-1.2.pom
Source52  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-fml/1.4/doxia-module-fml-1.4.jar
Source53  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-fml/1.4/doxia-module-fml-1.4.jar
Source54  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-fml/1.4/doxia-module-fml-1.4.pom
Source55  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-fml/1.4/doxia-module-fml-1.4.pom
Source56  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-fml/1.6/doxia-module-fml-1.6.jar
Source57  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-fml/1.6/doxia-module-fml-1.6.pom
Source58  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-fml/1.8/doxia-module-fml-1.8.jar
Source59  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-fml/1.8/doxia-module-fml-1.8.pom
Source60  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-markdown/1.6/doxia-module-markdown-1.6.jar
Source61  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-markdown/1.6/doxia-module-markdown-1.6.pom
Source62  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-markdown/1.7/doxia-module-markdown-1.7.jar
Source63  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-markdown/1.7/doxia-module-markdown-1.7.pom
Source64  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-markdown/1.8/doxia-module-markdown-1.8.jar
Source65  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-markdown/1.8/doxia-module-markdown-1.8.pom
Source66  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xdoc/1.0/doxia-module-xdoc-1.0.jar
Source67  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xdoc/1.0/doxia-module-xdoc-1.0.pom
Source68  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xdoc/1.6/doxia-module-xdoc-1.6.jar
Source69  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xdoc/1.6/doxia-module-xdoc-1.6.pom
Source70  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xdoc/1.7/doxia-module-xdoc-1.7.jar
Source71  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xdoc/1.7/doxia-module-xdoc-1.7.pom
Source72  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xdoc/1.8/doxia-module-xdoc-1.8.jar
Source73  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xdoc/1.8/doxia-module-xdoc-1.8.pom
Source74  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xhtml/1.0/doxia-module-xhtml-1.0.jar
Source75  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xhtml/1.0/doxia-module-xhtml-1.0.pom
Source76  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xhtml/1.1.2/doxia-module-xhtml-1.1.2.pom
Source77  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xhtml/1.2/doxia-module-xhtml-1.2.jar
Source78  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xhtml/1.2/doxia-module-xhtml-1.2.pom
Source79  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xhtml/1.2/doxia-module-xhtml-1.2.pom
Source80  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xhtml/1.4/doxia-module-xhtml-1.4.jar
Source81  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xhtml/1.4/doxia-module-xhtml-1.4.jar
Source82  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xhtml/1.4/doxia-module-xhtml-1.4.pom
Source83  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xhtml/1.4/doxia-module-xhtml-1.4.pom
Source84  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xhtml/1.6/doxia-module-xhtml-1.6.jar
Source85  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xhtml/1.6/doxia-module-xhtml-1.6.pom
Source86  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xhtml/1.8/doxia-module-xhtml-1.8.jar
Source87  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xhtml/1.8/doxia-module-xhtml-1.8.pom
Source88  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-modules/1.0/doxia-modules-1.0.pom
Source89  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-modules/1.1.2/doxia-modules-1.1.2.pom
Source90  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-modules/1.2/doxia-modules-1.2.pom
Source91  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-modules/1.2/doxia-modules-1.2.pom
Source92  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-modules/1.4/doxia-modules-1.4.pom
Source93  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-modules/1.4/doxia-modules-1.4.pom
Source94  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-modules/1.6/doxia-modules-1.6.pom
Source95  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-modules/1.7/doxia-modules-1.7.pom
Source96  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-modules/1.8/doxia-modules-1.8.pom
Source97  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-6/doxia-sink-api-1.0-alpha-6.jar
Source98  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-6/doxia-sink-api-1.0-alpha-6.pom
Source99  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-7/doxia-sink-api-1.0-alpha-7.jar
Source100  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-7/doxia-sink-api-1.0-alpha-7.pom
Source101  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-9/doxia-sink-api-1.0-alpha-9.jar
Source102  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-9/doxia-sink-api-1.0-alpha-9.pom
Source103  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.0/doxia-sink-api-1.0.jar
Source104  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.0/doxia-sink-api-1.0.pom
Source105  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.1.2/doxia-sink-api-1.1.2.jar
Source106  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.1.2/doxia-sink-api-1.1.2.pom
Source107  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.1/doxia-sink-api-1.1.jar
Source108  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.1/doxia-sink-api-1.1.pom
Source109  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.2/doxia-sink-api-1.2.jar
Source110  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.2/doxia-sink-api-1.2.pom
Source111  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.4/doxia-sink-api-1.4.jar
Source112  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.4/doxia-sink-api-1.4.pom
Source113  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.5/doxia-sink-api-1.5.jar
Source114  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.5/doxia-sink-api-1.5.pom
Source115  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.6/doxia-sink-api-1.6.jar
Source116  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.6/doxia-sink-api-1.6.pom
Source117  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.8/doxia-sink-api-1.8.jar
Source118  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.8/doxia-sink-api-1.8.pom
Source119  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia/1.0-alpha-10/doxia-1.0-alpha-10.pom
Source120  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia/1.0-alpha-6/doxia-1.0-alpha-6.pom
Source121  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia/1.0-alpha-7/doxia-1.0-alpha-7.pom
Source122  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia/1.0-alpha-9/doxia-1.0-alpha-9.pom
Source123  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia/1.0/doxia-1.0.pom
Source124  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia/1.1.2/doxia-1.1.2.pom
Source125  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia/1.1/doxia-1.1.pom
Source126  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia/1.2/doxia-1.2.pom
Source127  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia/1.4/doxia-1.4.pom
Source128  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia/1.5/doxia-1.5.pom
Source129  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia/1.6/doxia-1.6.pom
Source130  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia/1.8/doxia-1.8.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-doxia-data = %{version}-%{release}
Requires: mvn-doxia-license = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-doxia package.
Group: Data

%description data
data components for the mvn-doxia package.


%package license
Summary: license components for the mvn-doxia package.
Group: Default

%description license
license components for the mvn-doxia package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-doxia
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-doxia/LICENSE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.0
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.0/doxia-core-1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.7
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.7/doxia-module-fml-1.7.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.7
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.7/doxia-module-fml-1.7.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.7
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.7/doxia-module-xhtml-1.7.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.7
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.7/doxia-module-xhtml-1.7.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-10
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-10/doxia-sink-api-1.0-alpha-10.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.7
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.7/doxia-sink-api-1.7.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.7
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.7/doxia-sink-api-1.7.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.7
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.7/doxia-1.7.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.0
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.0/doxia-core-1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.1.2
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.1.2/doxia-core-1.1.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.2
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.2/doxia-core-1.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.2
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.2/doxia-core-1.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.4
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.4/doxia-core-1.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.4
cp %{SOURCE14} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.4/doxia-core-1.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.5
cp %{SOURCE15} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.5/doxia-core-1.5.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.5
cp %{SOURCE16} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.5/doxia-core-1.5.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.6
cp %{SOURCE17} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.6/doxia-core-1.6.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.6
cp %{SOURCE18} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.6/doxia-core-1.6.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.7
cp %{SOURCE19} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.7/doxia-core-1.7.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.7
cp %{SOURCE20} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.7/doxia-core-1.7.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.8
cp %{SOURCE21} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.8/doxia-core-1.8.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.8
cp %{SOURCE22} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.8/doxia-core-1.8.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.1.2
cp %{SOURCE23} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.1.2/doxia-logging-api-1.1.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.1.2
cp %{SOURCE24} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.1.2/doxia-logging-api-1.1.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.1
cp %{SOURCE25} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.1/doxia-logging-api-1.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.1
cp %{SOURCE26} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.1/doxia-logging-api-1.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.2
cp %{SOURCE27} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.2/doxia-logging-api-1.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.2
cp %{SOURCE28} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.2/doxia-logging-api-1.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.4
cp %{SOURCE29} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.4/doxia-logging-api-1.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.4
cp %{SOURCE30} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.4/doxia-logging-api-1.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.5
cp %{SOURCE31} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.5/doxia-logging-api-1.5.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.6
cp %{SOURCE32} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.6/doxia-logging-api-1.6.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.6
cp %{SOURCE33} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.6/doxia-logging-api-1.6.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.7
cp %{SOURCE34} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.7/doxia-logging-api-1.7.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.7
cp %{SOURCE35} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.7/doxia-logging-api-1.7.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.8
cp %{SOURCE36} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.8/doxia-logging-api-1.8.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.8
cp %{SOURCE37} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.8/doxia-logging-api-1.8.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.0
cp %{SOURCE38} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.0/doxia-module-apt-1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.0
cp %{SOURCE39} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.0/doxia-module-apt-1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.6
cp %{SOURCE40} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.6/doxia-module-apt-1.6.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.6
cp %{SOURCE41} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.6/doxia-module-apt-1.6.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.7
cp %{SOURCE42} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.7/doxia-module-apt-1.7.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.7
cp %{SOURCE43} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.7/doxia-module-apt-1.7.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.8
cp %{SOURCE44} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.8/doxia-module-apt-1.8.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.8
cp %{SOURCE45} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.8/doxia-module-apt-1.8.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.0
cp %{SOURCE46} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.0/doxia-module-fml-1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.0
cp %{SOURCE47} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.0/doxia-module-fml-1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.1.2
cp %{SOURCE48} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.1.2/doxia-module-fml-1.1.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.2
cp %{SOURCE49} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.2/doxia-module-fml-1.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.2
cp %{SOURCE50} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.2/doxia-module-fml-1.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.2
cp %{SOURCE51} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.2/doxia-module-fml-1.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.4
cp %{SOURCE52} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.4/doxia-module-fml-1.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.4
cp %{SOURCE53} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.4/doxia-module-fml-1.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.4
cp %{SOURCE54} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.4/doxia-module-fml-1.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.4
cp %{SOURCE55} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.4/doxia-module-fml-1.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.6
cp %{SOURCE56} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.6/doxia-module-fml-1.6.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.6
cp %{SOURCE57} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.6/doxia-module-fml-1.6.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.8
cp %{SOURCE58} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.8/doxia-module-fml-1.8.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.8
cp %{SOURCE59} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.8/doxia-module-fml-1.8.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-markdown/1.6
cp %{SOURCE60} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-markdown/1.6/doxia-module-markdown-1.6.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-markdown/1.6
cp %{SOURCE61} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-markdown/1.6/doxia-module-markdown-1.6.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-markdown/1.7
cp %{SOURCE62} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-markdown/1.7/doxia-module-markdown-1.7.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-markdown/1.7
cp %{SOURCE63} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-markdown/1.7/doxia-module-markdown-1.7.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-markdown/1.8
cp %{SOURCE64} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-markdown/1.8/doxia-module-markdown-1.8.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-markdown/1.8
cp %{SOURCE65} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-markdown/1.8/doxia-module-markdown-1.8.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.0
cp %{SOURCE66} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.0/doxia-module-xdoc-1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.0
cp %{SOURCE67} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.0/doxia-module-xdoc-1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.6
cp %{SOURCE68} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.6/doxia-module-xdoc-1.6.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.6
cp %{SOURCE69} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.6/doxia-module-xdoc-1.6.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.7
cp %{SOURCE70} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.7/doxia-module-xdoc-1.7.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.7
cp %{SOURCE71} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.7/doxia-module-xdoc-1.7.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.8
cp %{SOURCE72} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.8/doxia-module-xdoc-1.8.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.8
cp %{SOURCE73} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.8/doxia-module-xdoc-1.8.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.0
cp %{SOURCE74} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.0/doxia-module-xhtml-1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.0
cp %{SOURCE75} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.0/doxia-module-xhtml-1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.1.2
cp %{SOURCE76} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.1.2/doxia-module-xhtml-1.1.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.2
cp %{SOURCE77} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.2/doxia-module-xhtml-1.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.2
cp %{SOURCE78} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.2/doxia-module-xhtml-1.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.2
cp %{SOURCE79} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.2/doxia-module-xhtml-1.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.4
cp %{SOURCE80} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.4/doxia-module-xhtml-1.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.4
cp %{SOURCE81} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.4/doxia-module-xhtml-1.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.4
cp %{SOURCE82} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.4/doxia-module-xhtml-1.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.4
cp %{SOURCE83} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.4/doxia-module-xhtml-1.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.6
cp %{SOURCE84} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.6/doxia-module-xhtml-1.6.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.6
cp %{SOURCE85} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.6/doxia-module-xhtml-1.6.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.8
cp %{SOURCE86} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.8/doxia-module-xhtml-1.8.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.8
cp %{SOURCE87} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.8/doxia-module-xhtml-1.8.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.0
cp %{SOURCE88} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.0/doxia-modules-1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.1.2
cp %{SOURCE89} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.1.2/doxia-modules-1.1.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.2
cp %{SOURCE90} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.2/doxia-modules-1.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.2
cp %{SOURCE91} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.2/doxia-modules-1.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.4
cp %{SOURCE92} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.4/doxia-modules-1.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.4
cp %{SOURCE93} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.4/doxia-modules-1.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.6
cp %{SOURCE94} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.6/doxia-modules-1.6.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.7
cp %{SOURCE95} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.7/doxia-modules-1.7.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.8
cp %{SOURCE96} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.8/doxia-modules-1.8.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-6
cp %{SOURCE97} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-6/doxia-sink-api-1.0-alpha-6.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-6
cp %{SOURCE98} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-6/doxia-sink-api-1.0-alpha-6.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-7
cp %{SOURCE99} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-7/doxia-sink-api-1.0-alpha-7.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-7
cp %{SOURCE100} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-7/doxia-sink-api-1.0-alpha-7.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-9
cp %{SOURCE101} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-9/doxia-sink-api-1.0-alpha-9.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-9
cp %{SOURCE102} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-9/doxia-sink-api-1.0-alpha-9.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0
cp %{SOURCE103} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0/doxia-sink-api-1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0
cp %{SOURCE104} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0/doxia-sink-api-1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.1.2
cp %{SOURCE105} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.1.2/doxia-sink-api-1.1.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.1.2
cp %{SOURCE106} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.1.2/doxia-sink-api-1.1.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.1
cp %{SOURCE107} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.1/doxia-sink-api-1.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.1
cp %{SOURCE108} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.1/doxia-sink-api-1.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.2
cp %{SOURCE109} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.2/doxia-sink-api-1.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.2
cp %{SOURCE110} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.2/doxia-sink-api-1.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.4
cp %{SOURCE111} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.4/doxia-sink-api-1.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.4
cp %{SOURCE112} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.4/doxia-sink-api-1.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.5
cp %{SOURCE113} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.5/doxia-sink-api-1.5.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.5
cp %{SOURCE114} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.5/doxia-sink-api-1.5.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.6
cp %{SOURCE115} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.6/doxia-sink-api-1.6.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.6
cp %{SOURCE116} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.6/doxia-sink-api-1.6.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.8
cp %{SOURCE117} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.8/doxia-sink-api-1.8.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.8
cp %{SOURCE118} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.8/doxia-sink-api-1.8.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.0-alpha-10
cp %{SOURCE119} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.0-alpha-10/doxia-1.0-alpha-10.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.0-alpha-6
cp %{SOURCE120} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.0-alpha-6/doxia-1.0-alpha-6.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.0-alpha-7
cp %{SOURCE121} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.0-alpha-7/doxia-1.0-alpha-7.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.0-alpha-9
cp %{SOURCE122} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.0-alpha-9/doxia-1.0-alpha-9.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.0
cp %{SOURCE123} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.0/doxia-1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.1.2
cp %{SOURCE124} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.1.2/doxia-1.1.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.1
cp %{SOURCE125} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.1/doxia-1.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.2
cp %{SOURCE126} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.2/doxia-1.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.4
cp %{SOURCE127} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.4/doxia-1.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.5
cp %{SOURCE128} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.5/doxia-1.5.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.6
cp %{SOURCE129} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.6/doxia-1.6.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.8
cp %{SOURCE130} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.8/doxia-1.8.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.0/doxia-core-1.0.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.0/doxia-core-1.0.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.1.2/doxia-core-1.1.2.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.2/doxia-core-1.2.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.2/doxia-core-1.2.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.4/doxia-core-1.4.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.4/doxia-core-1.4.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.5/doxia-core-1.5.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.5/doxia-core-1.5.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.6/doxia-core-1.6.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.6/doxia-core-1.6.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.7/doxia-core-1.7.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.7/doxia-core-1.7.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.8/doxia-core-1.8.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.8/doxia-core-1.8.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.1.2/doxia-logging-api-1.1.2.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.1.2/doxia-logging-api-1.1.2.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.1/doxia-logging-api-1.1.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.1/doxia-logging-api-1.1.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.2/doxia-logging-api-1.2.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.2/doxia-logging-api-1.2.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.4/doxia-logging-api-1.4.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.4/doxia-logging-api-1.4.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.5/doxia-logging-api-1.5.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.6/doxia-logging-api-1.6.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.6/doxia-logging-api-1.6.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.7/doxia-logging-api-1.7.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.7/doxia-logging-api-1.7.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.8/doxia-logging-api-1.8.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.8/doxia-logging-api-1.8.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.0/doxia-module-apt-1.0.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.0/doxia-module-apt-1.0.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.6/doxia-module-apt-1.6.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.6/doxia-module-apt-1.6.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.7/doxia-module-apt-1.7.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.7/doxia-module-apt-1.7.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.8/doxia-module-apt-1.8.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.8/doxia-module-apt-1.8.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.0/doxia-module-fml-1.0.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.0/doxia-module-fml-1.0.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.1.2/doxia-module-fml-1.1.2.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.2/doxia-module-fml-1.2.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.2/doxia-module-fml-1.2.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.4/doxia-module-fml-1.4.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.4/doxia-module-fml-1.4.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.6/doxia-module-fml-1.6.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.6/doxia-module-fml-1.6.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.7/doxia-module-fml-1.7.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.7/doxia-module-fml-1.7.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.8/doxia-module-fml-1.8.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.8/doxia-module-fml-1.8.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-markdown/1.6/doxia-module-markdown-1.6.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-markdown/1.6/doxia-module-markdown-1.6.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-markdown/1.7/doxia-module-markdown-1.7.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-markdown/1.7/doxia-module-markdown-1.7.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-markdown/1.8/doxia-module-markdown-1.8.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-markdown/1.8/doxia-module-markdown-1.8.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.0/doxia-module-xdoc-1.0.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.0/doxia-module-xdoc-1.0.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.6/doxia-module-xdoc-1.6.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.6/doxia-module-xdoc-1.6.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.7/doxia-module-xdoc-1.7.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.7/doxia-module-xdoc-1.7.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.8/doxia-module-xdoc-1.8.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.8/doxia-module-xdoc-1.8.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.0/doxia-module-xhtml-1.0.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.0/doxia-module-xhtml-1.0.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.1.2/doxia-module-xhtml-1.1.2.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.2/doxia-module-xhtml-1.2.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.2/doxia-module-xhtml-1.2.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.4/doxia-module-xhtml-1.4.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.4/doxia-module-xhtml-1.4.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.6/doxia-module-xhtml-1.6.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.6/doxia-module-xhtml-1.6.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.7/doxia-module-xhtml-1.7.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.7/doxia-module-xhtml-1.7.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.8/doxia-module-xhtml-1.8.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.8/doxia-module-xhtml-1.8.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.0/doxia-modules-1.0.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.1.2/doxia-modules-1.1.2.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.2/doxia-modules-1.2.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.4/doxia-modules-1.4.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.6/doxia-modules-1.6.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.7/doxia-modules-1.7.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.8/doxia-modules-1.8.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-10/doxia-sink-api-1.0-alpha-10.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-6/doxia-sink-api-1.0-alpha-6.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-6/doxia-sink-api-1.0-alpha-6.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-7/doxia-sink-api-1.0-alpha-7.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-7/doxia-sink-api-1.0-alpha-7.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-9/doxia-sink-api-1.0-alpha-9.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-9/doxia-sink-api-1.0-alpha-9.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0/doxia-sink-api-1.0.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0/doxia-sink-api-1.0.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.1.2/doxia-sink-api-1.1.2.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.1.2/doxia-sink-api-1.1.2.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.1/doxia-sink-api-1.1.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.1/doxia-sink-api-1.1.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.2/doxia-sink-api-1.2.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.2/doxia-sink-api-1.2.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.4/doxia-sink-api-1.4.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.4/doxia-sink-api-1.4.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.5/doxia-sink-api-1.5.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.5/doxia-sink-api-1.5.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.6/doxia-sink-api-1.6.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.6/doxia-sink-api-1.6.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.7/doxia-sink-api-1.7.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.7/doxia-sink-api-1.7.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.8/doxia-sink-api-1.8.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.8/doxia-sink-api-1.8.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.0-alpha-10/doxia-1.0-alpha-10.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.0-alpha-6/doxia-1.0-alpha-6.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.0-alpha-7/doxia-1.0-alpha-7.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.0-alpha-9/doxia-1.0-alpha-9.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.0/doxia-1.0.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.1.2/doxia-1.1.2.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.1/doxia-1.1.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.2/doxia-1.2.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.4/doxia-1.4.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.5/doxia-1.5.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.6/doxia-1.6.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.7/doxia-1.7.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.8/doxia-1.8.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-doxia/LICENSE
