#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-doxia
Version  : 1.0
Release  : 3
URL      : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-core/1.0/doxia-core-1.0.jar
Source0  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-core/1.0/doxia-core-1.0.jar
Source1  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-core/1.0/doxia-core-1.0.pom
Source2  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-core/1.2/doxia-core-1.2.jar
Source3  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-core/1.2/doxia-core-1.2.pom
Source4  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-core/1.4/doxia-core-1.4.pom
Source5  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-core/1.6/doxia-core-1.6.jar
Source6  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-core/1.6/doxia-core-1.6.pom
Source7  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-core/1.7/doxia-core-1.7.jar
Source8  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-core/1.7/doxia-core-1.7.pom
Source9  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-core/1.8/doxia-core-1.8.jar
Source10  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-core/1.8/doxia-core-1.8.pom
Source11  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-logging-api/1.1/doxia-logging-api-1.1.jar
Source12  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-logging-api/1.1/doxia-logging-api-1.1.pom
Source13  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-logging-api/1.2/doxia-logging-api-1.2.pom
Source14  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-logging-api/1.4/doxia-logging-api-1.4.jar
Source15  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-logging-api/1.4/doxia-logging-api-1.4.pom
Source16  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-logging-api/1.6/doxia-logging-api-1.6.jar
Source17  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-logging-api/1.6/doxia-logging-api-1.6.pom
Source18  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-logging-api/1.7/doxia-logging-api-1.7.jar
Source19  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-logging-api/1.7/doxia-logging-api-1.7.pom
Source20  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-logging-api/1.8/doxia-logging-api-1.8.jar
Source21  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-logging-api/1.8/doxia-logging-api-1.8.pom
Source22  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-apt/1.0/doxia-module-apt-1.0.jar
Source23  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-apt/1.0/doxia-module-apt-1.0.pom
Source24  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-apt/1.7/doxia-module-apt-1.7.jar
Source25  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-apt/1.7/doxia-module-apt-1.7.pom
Source26  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-apt/1.8/doxia-module-apt-1.8.jar
Source27  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-apt/1.8/doxia-module-apt-1.8.pom
Source28  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-fml/1.0/doxia-module-fml-1.0.jar
Source29  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-fml/1.0/doxia-module-fml-1.0.pom
Source30  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-fml/1.2/doxia-module-fml-1.2.jar
Source31  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-fml/1.2/doxia-module-fml-1.2.pom
Source32  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-fml/1.2/doxia-module-fml-1.2.pom
Source33  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-fml/1.4/doxia-module-fml-1.4.jar
Source34  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-fml/1.4/doxia-module-fml-1.4.jar
Source35  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-fml/1.4/doxia-module-fml-1.4.pom
Source36  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-fml/1.4/doxia-module-fml-1.4.pom
Source37  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-fml/1.6/doxia-module-fml-1.6.jar
Source38  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-fml/1.6/doxia-module-fml-1.6.pom
Source39  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-fml/1.8/doxia-module-fml-1.8.jar
Source40  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-fml/1.8/doxia-module-fml-1.8.pom
Source41  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-markdown/1.7/doxia-module-markdown-1.7.jar
Source42  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-markdown/1.7/doxia-module-markdown-1.7.pom
Source43  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-markdown/1.8/doxia-module-markdown-1.8.jar
Source44  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-markdown/1.8/doxia-module-markdown-1.8.pom
Source45  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xdoc/1.0/doxia-module-xdoc-1.0.jar
Source46  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xdoc/1.0/doxia-module-xdoc-1.0.pom
Source47  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xdoc/1.7/doxia-module-xdoc-1.7.jar
Source48  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xdoc/1.7/doxia-module-xdoc-1.7.pom
Source49  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xdoc/1.8/doxia-module-xdoc-1.8.jar
Source50  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xdoc/1.8/doxia-module-xdoc-1.8.pom
Source51  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xhtml/1.0/doxia-module-xhtml-1.0.jar
Source52  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xhtml/1.0/doxia-module-xhtml-1.0.pom
Source53  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xhtml/1.2/doxia-module-xhtml-1.2.jar
Source54  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xhtml/1.2/doxia-module-xhtml-1.2.pom
Source55  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xhtml/1.2/doxia-module-xhtml-1.2.pom
Source56  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xhtml/1.4/doxia-module-xhtml-1.4.jar
Source57  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xhtml/1.4/doxia-module-xhtml-1.4.jar
Source58  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xhtml/1.4/doxia-module-xhtml-1.4.pom
Source59  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xhtml/1.4/doxia-module-xhtml-1.4.pom
Source60  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xhtml/1.6/doxia-module-xhtml-1.6.jar
Source61  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xhtml/1.6/doxia-module-xhtml-1.6.pom
Source62  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xhtml/1.8/doxia-module-xhtml-1.8.jar
Source63  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-module-xhtml/1.8/doxia-module-xhtml-1.8.pom
Source64  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-modules/1.0/doxia-modules-1.0.pom
Source65  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-modules/1.2/doxia-modules-1.2.pom
Source66  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-modules/1.2/doxia-modules-1.2.pom
Source67  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-modules/1.4/doxia-modules-1.4.pom
Source68  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-modules/1.4/doxia-modules-1.4.pom
Source69  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-modules/1.6/doxia-modules-1.6.pom
Source70  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-modules/1.7/doxia-modules-1.7.pom
Source71  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-modules/1.8/doxia-modules-1.8.pom
Source72  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-7/doxia-sink-api-1.0-alpha-7.jar
Source73  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-7/doxia-sink-api-1.0-alpha-7.pom
Source74  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.0/doxia-sink-api-1.0.jar
Source75  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.0/doxia-sink-api-1.0.pom
Source76  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.1/doxia-sink-api-1.1.jar
Source77  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.1/doxia-sink-api-1.1.pom
Source78  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.2/doxia-sink-api-1.2.pom
Source79  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.4/doxia-sink-api-1.4.jar
Source80  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.4/doxia-sink-api-1.4.pom
Source81  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.6/doxia-sink-api-1.6.jar
Source82  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.6/doxia-sink-api-1.6.pom
Source83  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.8/doxia-sink-api-1.8.jar
Source84  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia-sink-api/1.8/doxia-sink-api-1.8.pom
Source85  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia/1.0-alpha-10/doxia-1.0-alpha-10.pom
Source86  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia/1.0-alpha-7/doxia-1.0-alpha-7.pom
Source87  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia/1.0/doxia-1.0.pom
Source88  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia/1.1/doxia-1.1.pom
Source89  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia/1.2/doxia-1.2.pom
Source90  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia/1.4/doxia-1.4.pom
Source91  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia/1.6/doxia-1.6.pom
Source92  : https://repo1.maven.org/maven2/org/apache/maven/doxia/doxia/1.8/doxia-1.8.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-doxia-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-doxia package.
Group: Data

%description data
data components for the mvn-doxia package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.0
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.2
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.2
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.4
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.6
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.6
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.7
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.7
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.8
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.8

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.8
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.8

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.1
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.1
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.2
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.4
cp %{SOURCE14} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.4
cp %{SOURCE15} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.6
cp %{SOURCE16} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.6
cp %{SOURCE17} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.7
cp %{SOURCE18} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.7
cp %{SOURCE19} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.8
cp %{SOURCE20} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.8

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.8
cp %{SOURCE21} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.8

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.0
cp %{SOURCE22} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.0
cp %{SOURCE23} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.7
cp %{SOURCE24} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.7
cp %{SOURCE25} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.8
cp %{SOURCE26} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.8

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.8
cp %{SOURCE27} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.8

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.0
cp %{SOURCE28} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.0
cp %{SOURCE29} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.2
cp %{SOURCE30} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.2
cp %{SOURCE31} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.2
cp %{SOURCE32} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.4
cp %{SOURCE33} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.4
cp %{SOURCE34} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.4
cp %{SOURCE35} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.4
cp %{SOURCE36} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.6
cp %{SOURCE37} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.6
cp %{SOURCE38} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.8
cp %{SOURCE39} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.8

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.8
cp %{SOURCE40} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.8

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-markdown/1.7
cp %{SOURCE41} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-markdown/1.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-markdown/1.7
cp %{SOURCE42} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-markdown/1.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-markdown/1.8
cp %{SOURCE43} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-markdown/1.8

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-markdown/1.8
cp %{SOURCE44} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-markdown/1.8

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.0
cp %{SOURCE45} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.0
cp %{SOURCE46} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.7
cp %{SOURCE47} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.7
cp %{SOURCE48} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.8
cp %{SOURCE49} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.8

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.8
cp %{SOURCE50} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.8

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.0
cp %{SOURCE51} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.0
cp %{SOURCE52} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.2
cp %{SOURCE53} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.2
cp %{SOURCE54} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.2
cp %{SOURCE55} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.4
cp %{SOURCE56} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.4
cp %{SOURCE57} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.4
cp %{SOURCE58} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.4
cp %{SOURCE59} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.6
cp %{SOURCE60} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.6
cp %{SOURCE61} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.8
cp %{SOURCE62} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.8

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.8
cp %{SOURCE63} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.8

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.0
cp %{SOURCE64} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.2
cp %{SOURCE65} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.2
cp %{SOURCE66} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.4
cp %{SOURCE67} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.4
cp %{SOURCE68} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.6
cp %{SOURCE69} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.7
cp %{SOURCE70} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.8
cp %{SOURCE71} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.8

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-7
cp %{SOURCE72} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-7
cp %{SOURCE73} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0
cp %{SOURCE74} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0
cp %{SOURCE75} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.1
cp %{SOURCE76} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.1
cp %{SOURCE77} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.2
cp %{SOURCE78} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.4
cp %{SOURCE79} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.4
cp %{SOURCE80} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.6
cp %{SOURCE81} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.6
cp %{SOURCE82} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.8
cp %{SOURCE83} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.8

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.8
cp %{SOURCE84} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.8

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.0-alpha-10
cp %{SOURCE85} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.0-alpha-10

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.0-alpha-7
cp %{SOURCE86} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.0-alpha-7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.0
cp %{SOURCE87} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.1
cp %{SOURCE88} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.2
cp %{SOURCE89} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.2

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.4
cp %{SOURCE90} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.6
cp %{SOURCE91} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.8
cp %{SOURCE92} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.8


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.0/doxia-core-1.0.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.0/doxia-core-1.0.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.2/doxia-core-1.2.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.2/doxia-core-1.2.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.4/doxia-core-1.4.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.6/doxia-core-1.6.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.6/doxia-core-1.6.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.7/doxia-core-1.7.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.7/doxia-core-1.7.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.8/doxia-core-1.8.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-core/1.8/doxia-core-1.8.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.1/doxia-logging-api-1.1.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.1/doxia-logging-api-1.1.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.2/doxia-logging-api-1.2.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.4/doxia-logging-api-1.4.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.4/doxia-logging-api-1.4.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.6/doxia-logging-api-1.6.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.6/doxia-logging-api-1.6.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.7/doxia-logging-api-1.7.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.7/doxia-logging-api-1.7.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.8/doxia-logging-api-1.8.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.8/doxia-logging-api-1.8.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.0/doxia-module-apt-1.0.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.0/doxia-module-apt-1.0.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.7/doxia-module-apt-1.7.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.7/doxia-module-apt-1.7.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.8/doxia-module-apt-1.8.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-apt/1.8/doxia-module-apt-1.8.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.0/doxia-module-fml-1.0.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.0/doxia-module-fml-1.0.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.2/doxia-module-fml-1.2.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.2/doxia-module-fml-1.2.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.4/doxia-module-fml-1.4.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.4/doxia-module-fml-1.4.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.6/doxia-module-fml-1.6.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.6/doxia-module-fml-1.6.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.8/doxia-module-fml-1.8.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-fml/1.8/doxia-module-fml-1.8.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-markdown/1.7/doxia-module-markdown-1.7.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-markdown/1.7/doxia-module-markdown-1.7.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-markdown/1.8/doxia-module-markdown-1.8.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-markdown/1.8/doxia-module-markdown-1.8.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.0/doxia-module-xdoc-1.0.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.0/doxia-module-xdoc-1.0.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.7/doxia-module-xdoc-1.7.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.7/doxia-module-xdoc-1.7.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.8/doxia-module-xdoc-1.8.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xdoc/1.8/doxia-module-xdoc-1.8.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.0/doxia-module-xhtml-1.0.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.0/doxia-module-xhtml-1.0.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.2/doxia-module-xhtml-1.2.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.2/doxia-module-xhtml-1.2.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.4/doxia-module-xhtml-1.4.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.4/doxia-module-xhtml-1.4.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.6/doxia-module-xhtml-1.6.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.6/doxia-module-xhtml-1.6.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.8/doxia-module-xhtml-1.8.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-module-xhtml/1.8/doxia-module-xhtml-1.8.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.0/doxia-modules-1.0.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.2/doxia-modules-1.2.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.4/doxia-modules-1.4.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.6/doxia-modules-1.6.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.7/doxia-modules-1.7.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-modules/1.8/doxia-modules-1.8.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-7/doxia-sink-api-1.0-alpha-7.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-7/doxia-sink-api-1.0-alpha-7.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0/doxia-sink-api-1.0.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0/doxia-sink-api-1.0.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.1/doxia-sink-api-1.1.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.1/doxia-sink-api-1.1.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.2/doxia-sink-api-1.2.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.4/doxia-sink-api-1.4.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.4/doxia-sink-api-1.4.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.6/doxia-sink-api-1.6.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.6/doxia-sink-api-1.6.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.8/doxia-sink-api-1.8.jar
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.8/doxia-sink-api-1.8.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.0-alpha-10/doxia-1.0-alpha-10.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.0-alpha-7/doxia-1.0-alpha-7.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.0/doxia-1.0.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.1/doxia-1.1.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.2/doxia-1.2.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.4/doxia-1.4.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.6/doxia-1.6.pom
/usr/share/java/.m2/repository/org/apache/maven/doxia/doxia/1.8/doxia-1.8.pom
